import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
import { AuthProvider } from "@/script/authContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">

            <body className={inter.className}>
                <AuthProvider>
                    {children}
                </AuthProvider>
            </body>

        </html>
    );
}