import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/script/cartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <CartProvider>
        <body className={inter.className}>
          {children}
        </body>
      </CartProvider>
    </html>
  );
}