import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Capa from "@/components/capa";
import Menu from "@/components/footerMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <main className="relative z-10 self-center">
          <Header />
          <Capa />
          {children}
          <Menu />
        </main>
      </body>
    </html>
  );
}